add file

diff --git a/poornames b/poornames
--- a/poornames
+++ b/poornames
@@ -1,94 +1,109 @@
-#! /usr/bin/sh
+#!/bin/bash
 
-#Allow hidden files to be read
-shopt -s dotglob
-
-#######################################################################
-## Functions                                                         ##
-#######################################################################
-
-usage(){ printf "\nUsage: ./poornames [directoryName]\n\n" 1>&2; }
-
-alreadyExists(){
-    toCheck=$(echo $1 | tr '[:upper:]' '[:lower:]')
-    shift
-    tempArr=("$@")
-    for item in $@; do
-	if [[ "$toCheck" == "$item" ]]; then
-	    return 0
-	fi
-    done
-    return 1
+#CHECK FOR REPEATS GIVEN FILE NAME + ARRAY OF USED NAMES
+repeat(){
+        check=$(echo $1 | tr '[:upper:]' '[:lower:]')
+        for i in $2;
+        do
+                if [[ "$check" == "$i" ]]; then
+                        return 0
+                fi
+        done
+        return 1
 }
 
-checker(){
-    declare -a validNames
-    
-    for x in $1/*; do
-	if [[ ! $x =~ $1/[_A-Za-z][_A-Za-z\.\-]{0,13}$ ]] ; then
-	    printf "$x\n"
-	elif alreadyExists $x ${validNames[@]} ; then
-	    printf "$x\n"
-	else
-	    validNames+=($(echo $x | tr 'A-Z' 'a-z'))
-	    
-	    #If valid and is a directory
-	    #Follow directory and run checker on it
-	    if [ -d $x ]; then
-		if [ -r $x ]; then
-		    checker $x
-		else
-		    printf "ERROR: Cannot read $x : Permission Denied\n" 1>&2
-		    printf "\tRead permissions required...\n" 1>&2
-	        fi
-	    fi   
-	fi
-    done
-}
-                                                                                                                                                                
-#######################################################################
-## Check arguments...                                                ##
-#######################################################################
 
-#If no arguments, make it current directory
-#If . make it current directory
+#RECURSIVE BLOCK
+checkR(){
+	declare -a usedNames
+        for file in "$1"/*
+        do
+		if [ -d $file ]; then
+			if [ -r $file ]; then
+      	                     	if [[ ! $file =~ $1/[_A-Za-z][_A-Za-z\.\-]{0,13}$ ]]; then
+                	        	printf "%s\n" "$file"
+               			elif repeat $file $usedNames ; then
+                        		printf "%s\n" "$file"
+                		else
+                        		usedNames+=($(echo $file | tr 'A-Z' 'a-z'))
+                		fi
+			     	checkR $file
+                        else
+                             	printf "Cannot read $file .\n" 1>&2
+                        fi
+                elif [[ ! $file =~ $1/[_A-Za-z][_A-Za-z\.\-]{0,13}$ ]]; then
+                        printf "%s\n" "$file"
+                elif repeat $file $usedNames ; then
+                        printf "%s\n" "$file"
+                else
+                        usedNames+=($(echo $file | tr 'A-Z' 'a-z'))
+                        if [ ! -r $file ]; then
+                             	printf "Cannot read $file.\n" 1>&2
+			fi
+                fi
+        done
+	
+}
+
+#NON_RECURSIVE BLOCK
+check(){
+        declare -a usedNames
+
+        for file in "$1"/*
+        do
+                if [[ ! $file =~ $1/[_A-Za-z][_A-Za-z\.\-]{0,13}$ ]]; then
+                        printf "%s\n" "$file"
+                elif repeat $file $usedNames ; then
+                        printf "%s\n" "$file"
+                else
+                        usedNames+=($(echo $file | tr 'A-Z' 'a-z'))
+			if [ ! -r $file ]; then
+				printf "Cannot read $file.\n" 1>&2
+			fi
+                fi
+        done
+}
+
+#CHECK FOR -r OPTION
+recursive="false"
+if [ $1 == "-r" ]; then
+	recursive="true"
+	shift
+fi
+
+#check if the given is not a directory/exists/symbolic link
+if [ ! -d $1 ]; then
+        printf "$1 is not a directory.\n" 1>&2
+        exit 1
+elif [ -L $1 ]; then
+        printf "$1 is a symbolic link.\n" 1>&2
+        exit 1
+fi
+
+#if no directory or . is given, using current directory
 if [ $# -eq 0 ]; then
-    dir=`pwd`
+    d=`pwd`
 elif [ $1 == "." ]; then
-    dir=`pwd`
+    d=`pwd`
 else
-    dir=$1
+    d=$1
 fi
 
-
-if [[ $dir =~ /$ ]]; then
-    dir=$(echo $dir | sed s/.$//)
-fi
-
-
-#Check if not more than 1 argument
+#check if too many arguments
 if [ $# -gt 1 ]; then
-    printf "ERROR: Too mamy arguments\n" 1>&2
-    usage
-    exit 1
-fi
-
-#Check if argument starts with -
-if [ ${dir:0:1} = '-' ]; then
-    printf "ERROR: Argument cannot have \'-\'\n" 1>&2
+    printf "Only one directory required. Too many provided.\n" 1>&2
     exit 2
-fi
-
-#Check if argument is a directory
-if [ ! -d $dir ]; then
-    printf "ERROR: $dir is NOT a directory\n" 1>&2
+#check if starts with -
+elif [ "${dir:0:1}" == '-' ]; then
+    printf "Argument cannot start with \'-\'\n" 1>&2
     exit 3
 fi
 
-#######################################################################
-## Run file name checking function...                                ##
-#######################################################################
+#ONCE ARGUMENT CHECKED, RUN RECURSIVE/NON RECURSIVE OPTION DEPENDING
+#ON -r EXISTENCE
+if [ $recursive == "true" ]; then
+	checkR $d
+else
+	check $d
+fi
 
-checker $dir
-
-#######################################################################
